version: "3.9"
services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - sqlite_db:/app/db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      back:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  sqlite_db:
