/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  Article: { // root type
    content: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    isPublished: boolean; // Boolean!
    label: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  ArticleComment: { // root type
    content: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    isValidated: boolean; // Boolean!
    note?: number | null; // Int
  }
  Category: { // root type
    id: number; // Int!
    label: string; // String!
  }
  Follow: { // root type
    id: number; // Int!
  }
  Image: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    url: string; // String!
  }
  Query: {};
  Tag: { // root type
    id: number; // Int!
    label: string; // String!
  }
  Writer: { // root type
    avatar: string; // String!
    blogLabel: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string; // String!
    email: string; // String!
    id: number; // Int!
    password: string; // String!
    pseudo: string; // String!
    role: string; // String!
  }
  WriterComment: { // root type
    content: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    isValidated: boolean; // Boolean!
    note?: number | null; // Int
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Article: { // field return type
    comments: NexusGenRootTypes['ArticleComment'][] | null; // [ArticleComment!]
    content: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    isPublished: boolean; // Boolean!
    label: string; // String!
    publishedBy: NexusGenRootTypes['Writer'] | null; // Writer
    tags: NexusGenRootTypes['Tag'][] | null; // [Tag!]
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  ArticleComment: { // field return type
    content: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    isValidated: boolean; // Boolean!
    note: number | null; // Int
    publishedBy: NexusGenRootTypes['Writer'] | null; // Writer
    publishedOn: NexusGenRootTypes['Article'] | null; // Article
  }
  Category: { // field return type
    id: number; // Int!
    label: string; // String!
    writers: NexusGenRootTypes['Writer'][] | null; // [Writer!]
  }
  Follow: { // field return type
    followed: NexusGenRootTypes['Writer'] | null; // Writer
    following: NexusGenRootTypes['Writer'] | null; // Writer
    id: number; // Int!
  }
  Image: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    ownedBy: NexusGenRootTypes['Writer'] | null; // Writer
    url: string; // String!
  }
  Query: { // field return type
    getAllArticles: NexusGenRootTypes['Article'][]; // [Article!]!
  }
  Tag: { // field return type
    articles: NexusGenRootTypes['Article'][] | null; // [Article!]
    id: number; // Int!
    label: string; // String!
  }
  Writer: { // field return type
    articles: NexusGenRootTypes['Article'][] | null; // [Article!]
    avatar: string; // String!
    blogLabel: string; // String!
    category: NexusGenRootTypes['Category'] | null; // Category
    commentsFromWriters: NexusGenRootTypes['ArticleComment'][] | null; // [ArticleComment!]
    commentsOnArticles: NexusGenRootTypes['ArticleComment'][] | null; // [ArticleComment!]
    commentsOnWriters: NexusGenRootTypes['ArticleComment'][] | null; // [ArticleComment!]
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string; // String!
    email: string; // String!
    followers: NexusGenRootTypes['Follow'][] | null; // [Follow!]
    following: NexusGenRootTypes['Follow'][] | null; // [Follow!]
    id: number; // Int!
    images: NexusGenRootTypes['Image'][] | null; // [Image!]
    password: string; // String!
    pseudo: string; // String!
    role: string; // String!
  }
  WriterComment: { // field return type
    content: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    isValidated: boolean; // Boolean!
    note: number | null; // Int
    writtenBy: NexusGenRootTypes['Writer'] | null; // Writer
    writtenOn: NexusGenRootTypes['Writer'] | null; // Writer
  }
}

export interface NexusGenFieldTypeNames {
  Article: { // field return type name
    comments: 'ArticleComment'
    content: 'String'
    createdAt: 'DateTime'
    id: 'Int'
    isPublished: 'Boolean'
    label: 'String'
    publishedBy: 'Writer'
    tags: 'Tag'
    updatedAt: 'DateTime'
  }
  ArticleComment: { // field return type name
    content: 'String'
    createdAt: 'DateTime'
    id: 'Int'
    isValidated: 'Boolean'
    note: 'Int'
    publishedBy: 'Writer'
    publishedOn: 'Article'
  }
  Category: { // field return type name
    id: 'Int'
    label: 'String'
    writers: 'Writer'
  }
  Follow: { // field return type name
    followed: 'Writer'
    following: 'Writer'
    id: 'Int'
  }
  Image: { // field return type name
    createdAt: 'DateTime'
    id: 'Int'
    ownedBy: 'Writer'
    url: 'String'
  }
  Query: { // field return type name
    getAllArticles: 'Article'
  }
  Tag: { // field return type name
    articles: 'Article'
    id: 'Int'
    label: 'String'
  }
  Writer: { // field return type name
    articles: 'Article'
    avatar: 'String'
    blogLabel: 'String'
    category: 'Category'
    commentsFromWriters: 'ArticleComment'
    commentsOnArticles: 'ArticleComment'
    commentsOnWriters: 'ArticleComment'
    createdAt: 'DateTime'
    description: 'String'
    email: 'String'
    followers: 'Follow'
    following: 'Follow'
    id: 'Int'
    images: 'Image'
    password: 'String'
    pseudo: 'String'
    role: 'String'
  }
  WriterComment: { // field return type name
    content: 'String'
    createdAt: 'DateTime'
    id: 'Int'
    isValidated: 'Boolean'
    note: 'Int'
    writtenBy: 'Writer'
    writtenOn: 'Writer'
  }
}

export interface NexusGenArgTypes {
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}