name: front-tests-workflow.yml

on: pull_request

jobs:
  test-front:
  runs-on: ubuntu-latest
  steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Goto client and run tests
      run: cd front && npm i && npm test
